### ISSUE TITLE
Remove reference data and "gscd_code" column

### ISSUE THREAD

**Issue by gnodnooh** [chc-ucsb/HarvestStat#22]
Remove "original" data in the output files, which flagged as "gscd_code = reported". We don't need to provide it for reference as the data changes over time. Therefore, we don't need to flag "gscd_code = calibrated" as well.

**Comment by gnodnooh** [comment]
The feature of "gscd_code" is deprecated.

**Comment by WestonAnderson** [comment]
Hi Donghoon,

Just to clarify this. By flagging this as deprecated it means I should remove the following lines of code from the scripts, correct?

# Reported FDW data ----------------------------- #
stack_fdw = df[names]
stack_fdw['indicator'] = stack_fdw['indicator'].replace({'Area Harvested':'area','Quantity Produced':'production','Yield':'yield'})
stack_fdw['gscd_code'] = 'reported'
stack = pd.concat([stack_fdw,stack_gscd], axis=0).reset_index(drop=True)
# ----------------------------------------------- #

and instead simply rename "stack = stack_gcsd" correct?

**Comment by gnodnooh** [comment]
Hi Weston,

That is correct. We don't include original data and use gscd_code anymore. Just remove that code block of
```python
# Reported FDW data ----------------------------- #
...
# ------------------------------------------------- #
```

This is the updated structure:
```python
# Manual correction ----------------------------- #
crop_new = prod_new/area_new
# ----------------------------------------------- #

# Complete long format DataFrame ---------------- #
df_area = area_new.T.stack().rename('value').reset_index()
df_area['indicator'] = 'area'
df_prod = prod_new.T.stack().rename('value').reset_index()
df_prod['indicator'] = 'production'
df_yield = (prod_new/area_new).T.stack().rename('value').reset_index()
df_yield['indicator'] = 'yield'
stack = pd.concat([df_area, df_prod, df_yield], axis=0)
# Add "planting year"
cols = ['season_name','product','crop_production_system','planting_month','harvest_year','harvest_month','planting_year']
season_table = df[cols].drop_duplicates()
stack = stack.merge(season_table, on=cols[:-1])
# Add country and admin names
stack = stack.merge(df[['fnid','country','country_code','admin_1','admin_2']].drop_duplicates(), on='fnid', how='inner')
names = [
    'fnid','country','country_code','admin_1','admin_2','name',
    'product','season_name','planting_year','planting_month','harvest_year','harvest_month',
    'crop_production_system','indicator','value'
]
stack = stack[names]
# ----------------------------------------------- #

# Final Processing ------------------------------ #
# Manual change of product name
product_category_custom = {
    'Maize (Corn)':'Maize',
    'Rice (Paddy)':'Rice',
...
```

stack is finally organized by ```stack = stack[names]```.
