### ISSUE TITLE
Existing admin-1 data VS Aggregated admin-1 data

### ISSUE THREAD

**Issue by gnodnooh** [chc-ucsb/HarvestStat#24]
What countries have data in both resolutions? 
If the admin_1 is for specific "population_group", we can exclude it and go with aggregated admin_1 data.

**Comment by gnodnooh** [comment]
Hi @WestonAnderson, since we decide to use full resolution, shall we close this one?

**Comment by WestonAnderson** [comment]
Yes, let's close this one

**Comment by gnodnooh** [comment]
I close this.
